In [8]:
import pandas as pd
import numpy as np

In [9]:
from google.colab import files
uploaded = files.upload()

Saving amsPrediction - Sheet1.csv to amsPrediction - Sheet1.csv


In [12]:
uploaded


{'amsPrediction - Sheet1.csv': b'Attendance,MSE,HRS,ESE\r\n70,10,17,42\r\n92,7,20,39\r\n67,3,18,32\r\n82,16,13,50\r\n80,9,10,44\r\n72,11,16,55\r\n85,7,18,43\r\n75,10,14,37\r\n80,8,14,43\r\n70,8,14,41\r\n85,8,16,48\r\n65,12,17,61\r\n70,4,17,44\r\n75,7,19,45\r\n80,15,20,58\r\n85,12,19,52\r\n75,6,15,45\r\n68,9,22,46\r\n65,10,19,46\r\n95,7,20,40\r\n90,13,12,57\r\n78,5,8,42\r\n78,8,2,35\r\n80,12,2,52\r\n85,17,20,64\r\n95,11,12,47\r\n78,10,5,42\r\n79,16,20,52\r\n65,17,14,55\r\n98,12,11,50\r\n98,11,9,53\r\n68,13,14,50\r\n88,11,14,51\r\n75,10,11,49\r\n88,7,3,39\r\n88,6,4,39\r\n88,9,7,49\r\n90,9,13,52\r\n75,12,13,49\r\n98,11,20,45\r\n95,6,5,36\r\n98,7,4,35\r\n78,14,8,50\r\n95,12,6,43\r\n75,10,5,49\r\n77,14,5,57\r\n85,5,8,38\r\n70,6,9,41\r\n95,11,20,46\r\n95,9,8,50\r\n75,9,7,51\r\n90,8,8,38\r\n90,9,20,49\r\n96,6,12,44\r\n94,10,13,41\r\n80,17,18,57\r\n75,11,6,45\r\n78,11,20,49\r\n82,10,21,49\r\n80,8,7,50\r\n80,7,12,44\r\n92,7,15,40\r\n85,10,14,50\r\n68,11,9,43\r\n88,7,5,36\r\n80,12,18,50\r\n62,8,

In [13]:
import io

In [14]:
df = pd.read_csv(io.StringIO(uploaded["amsPrediction - Sheet1.csv"].decode("utf-8")))
df.head()

Attendance  MSE  HRS  ESE
0          70   10   17   42
1          92    7   20   39
2          67    3   18   32
3          82   16   13   50
4          80    9   10   44

In [15]:
df.describe()

Attendance        MSE        HRS        ESE
count   73.000000  73.000000  73.000000  73.000000
mean    81.698630   9.780822  12.904110  46.630137
std      9.506847   3.047069   5.701278   6.617542
min     62.000000   3.000000   2.000000  32.000000
25%     75.000000   8.000000   8.000000  42.000000
50%     80.000000  10.000000  14.000000  47.000000
75%     90.000000  11.000000  18.000000  50.000000
max     98.000000  17.000000  22.000000  64.000000

In [16]:
endog = df["ESE"].head()
exog = df[["MSE","Attendance", "HRS"]].head()
print(exog)

   MSE  Attendance  HRS
0   10          70   17
1    7          92   20
2    3          67   18
3   16          82   13
4    9          80   10


In [17]:
X = exog.to_numpy()
Y = endog.to_numpy()
print(X)

[[10 70 17]
 [ 7 92 20]
 [ 3 67 18]
 [16 82 13]
 [ 9 80 10]]


In [18]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [19]:
M = mean(X.T, axis = 1)
print(M)

[ 9.  78.2 15.6]


In [20]:
C = X-M
print(C)

[[  1.   -8.2   1.4]
 [ -2.   13.8   4.4]
 [ -6.  -11.2   2.4]
 [  7.    3.8  -2.6]
 [  0.    1.8  -5.6]]


In [21]:
V = cov(C.T)
print(V)

[[ 22.5  14.5 -10. ]
 [ 14.5 100.2   0.6]
 [-10.    0.6  16.3]]


In [22]:
values, vectors = eig(V)
print(values)
print(vectors)

[102.83421474  28.19086641   7.97491885]
[[-0.1792837  -0.75344094  0.63260107]
 [-0.98369925  0.14637427 -0.10445268]
 [ 0.01389759  0.64101586  0.7674018 ]]


In [23]:
P = vectors.T.dot(C.T)
print(P.T)

[[  7.90650678  -1.05628772   2.56347554]
 [-13.15533283   6.34731651   0.66991886]
 [ 12.126488     4.4196919   -0.7839721 ]
 [ -5.02917677  -6.38450557   2.03604261]
 [ -1.84848518  -3.32621512  -4.48546492]]


In [24]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalcomponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalcomponents, columns = ["principal Component 1"])

In [25]:
import statsmodels.api as sm
exog1 = sm.add_constant(principalDf[["principal Component 1"]])
print(exog1)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


   const  principal Component 1
0    1.0              -7.906507
1    1.0              13.155333
2    1.0             -12.126488
3    1.0               5.029177
4    1.0               1.848485


In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
lr = LinearRegression()

In [28]:
model = lr.fit(exog1, endog)

In [29]:
lr.coef_

array([0.       , 0.3056601])

In [30]:
lr.intercept_

41.4

In [31]:
import math
def RSE(y_true, y_predicted):
  y_true = np.array(y_true)
  y_predicted = np.array(y_predicted)
  RSS = np.sum(np.square(y_true-y_predicted))
  rse = math.sqrt(RSS/(len(y_true)-2))
  return rse

In [33]:
ypred = lr.predict(exog1)

In [34]:
re = RSE(endog, ypred)
print(re)

6.752026356402884
